from elasticsearch import Elasticsearch

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "changeme"

# Create the client instance

es = Elasticsearch(hosts="http://elastic:changeme@127.0.0.1:9200/")


# es = Elasticsearch(['http://localhost:9200'], http_auth=('elastic', 'changeme'))
# Successful response!
print(es.info())
