from elasticsearch import Elasticsearch
import json

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "changeme"

# Create the client instance

es = Elasticsearch(hosts="http://elastic:changeme@127.0.0.1:9200/")


# es = Elasticsearch(['http://localhost:9200'], http_auth=('elastic', 'changeme'))
# Successful response!
print(es.info())

matching_terms = "2021 Australian grand pix"
# query = {
#     "query": {
#         "multi_match": {
#             "query": matching_terms,
#             "type": "best_fields",
#             "fields": ["title^3", "summary^2", "text", "keywords^2"],
#             "tie_breaker": 0.3
#         }
#     }
# }


query = {
    "query": {
        "bool": {
            "must": {

                "multi_match": {
                    "query": matching_terms,
                    "type": "best_fields",
                    "fields": ["title^3", "summary^2", "text", "keywords^2"],
                    "tie_breaker": 0.3
                }
            },
            "filter": {
                "range": {
                    "publish_date": {
                        "gte": "2021-02-05T00:00:00.000Z",
                        "lte": "2021-02-10T00:00:00.000Z"
                    }
                },
                "term" :{
                        "newspaper.keyword": ["BBC", "CNN"]
                     }
            }
        }
    }
}

query = json.dumps(query)

resp = es.search(index="temp_index", body=query,)
print("Got %d Hits:" % resp['hits']['total']['value'])
for hit in resp['hits']['hits']:
    print("%(publish_date)s %(title)s: \n %(summary)s" % hit["_source"])
# print(resp)
