from elasticsearch import Elasticsearch
import json

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "changeme"

# Create the client instance

es = Elasticsearch(hosts="http://elastic:changeme@127.0.0.1:9200/")


# es = Elasticsearch(['http://localhost:9200'], http_auth=('elastic', 'changeme'))
# Successful response!
print(es.info())

matching_terms = "2021 Australian grand pix"
start_date = "2022-09-05"
end_date = "2022-09-15"
news_channel = ["BBC", "CNN"]
# query = {
#     "query": {
#         "multi_match": {
#             "query": matching_terms,
#             "type": "best_fields",
#             "fields": ["title^3", "summary^2", "text", "keywords^2"],
#             "tie_breaker": 0.3
#         }
#     }
# }

query = {
    "from": 0,
    "size": 1,
    "query": {
        "bool": {
            "must": {
                "multi_match": {
                    "query": matching_terms,
                    "type": "best_fields",
                    "fields": ["title^3", "summary^2", "text", "keywords^2"],
                    "tie_breaker": 0.3
                }
            },
            "filter": [
                {
                    "range": {
                        "publish_date": {
                            "gte": start_date,
                            "lte": end_date
                        }
                    }
                },
                {
                    "terms": {
                        "newspaper.keyword": news_channel
                    }
                }
            ]

        }
    }
}

query = json.dumps(query)
print(query)

resp = es.search(index="temp_index", body=query,)
print("Got %d Hits:" % resp['hits']['total']['value'])
for hit in resp['hits']['hits']:
    print("%(publish_date)s %(title)s: \n %(summary)s" % hit["_source"])
# print(resp)
